name: movies_aa2
services:
  db:
    image: mariadb:11.3.2
    container_name: movies-db-aa2
    environment:
      MYSQL_USER: $MARIADB_USER
      MYSQL_PASSWORD: $MARIADB_PASSWORD
      MYSQL_DATABASE: $MARIADB_DATABASE
      MYSQL_PORT: 3308
      MYSQL_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
    ports:
      - "3308:3306"
    volumes:
      - C:/Users/Cristina/Documents/mariadb_aa2:/var/lib/mysql
