spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3308/movies_aa2}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cristina}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

logging.level.org.springframework=ERROR